README.md

Leslies attempt

---

README.md

add my full name

---

package.json
server/db/models/ingredient.js
server/db/models/user.js

modified user and added ingredient table

---

package-lock.json
server/db/models/index.js
server/db/models/noodle.js
server/db/models/order.js

finished order and noodle models

---

server/auth/google.js

oauth changes

---

package-lock.json
script/seed.js
server/db/models/index.js

added associations and seeding tests

---

server/api/noodles.js
server/api/users.js
server/auth/index.js

done with routes

---

script/seed.js

added 20 users

---

script/seed.js
server/db/models/noodle.js

added dummyNoodles data

---

client/components/AllNoodles.js
client/components/Cart.js
client/components/SingleNoodle.js
client/store/noodles.js
package.json

Components

---

client/components/SingleNoodle.js
client/routes.js
server/api/index.js
server/api/noodles.js

worked on singleNoodle Component and added backend noodle routes

---

client/components/AllNoodles.js
client/store/index.js
client/store/noodles.js

All Noodles Component is functional

---

client/components/AllNoodles.js
client/components/SingleNoodle.js

added button to singlenoodle

---

.travis.yml

added travis, travis-token

---

script/seed.js
server/db/models/index.js
server/db/models/orderItem.js

added quantity in throught table

---

client/components/auth-form.js
server/api/orders.js
server/auth/index.js

added initial backend order routes

---

client/store/cart.js

fixed store/cart.js

---

server/api/users.js

added security to users/isAdmin

---

client/components/OrderConfirmation.js
client/components/UserProfile.js
client/components/user-home.js
client/routes.js

small changes to Components

---

client/components/Cart.js
client/components/CartColumns.js
client/components/CartItem.js
client/components/CartList.js
public/index.html
server/api/orders.js

checkout 40% done

---

client/components/AllNoodles.js
client/components/navbar.js
client/components/user-home.js
server/auth/index.js

working on edit and remove noodle

---

client/components/AllNoodles.js
client/components/UpdateNoodle.js
client/store/noodles.js

added Admin access functionality. Working

---

client/components/Cart.js
client/components/Checkout.js
client/store/cart.js
server/api/orders.js

80%checkout

---

client/components/user-home.js
server/api/users.js

passing test specs

---

client/components/AllNoodles.js

fixed add noodle

---

client/components/auth-form.js
client/store/user.js
script/seed.js
server/db/models/noodle.js
server/db/models/order.js
server/db/models/orderItem.js

Order routes

---

server/api/index.js
server/api/noodles.js
server/api/orders.js
server/api/users.js
server/api/utils.js

wrote middleware for admin/user

---

client/components/AllNoodles.js
client/components/UpdateNoodle.js
client/components/auth-form.js
client/components/user-home.js
client/routes.js
client/store/cart.js
script/seed.js
server/api/orders.js

got user to load their cart in DB

---

server/api/orders.js
server/api/users.js
server/api/utils.js
server/auth/index.js

fixed middleware for routes

---

client/components/SingleNoodle.js
client/store/cart.js
script/seed.js
server/api/orders.js
server/db/models/order.js

doing order routes

---

client/components/SingleNoodle.js
client/store/cart.js
server/api/orders.js
server/api/utils.js
server/db/models/orderItem.js

added add function

---

client/components/CartItem.js
client/store/cart.js
server/api/orders.js
server/auth/index.js

Tier 1 90%

---

client/components/user-home.js
client/store/cart.js
client/store/user.js

added get and remove cart functionality

---

react-express-stripe/backend/routes/index.js
react-express-stripe/backend/routes/payment.js

made some small changes to userorder

---

client/store/cart.js
client/store/user.js
server/api/orders.js

Local storage

---

client/store/cart.js
client/store/user.js

Merge cart

---

client/store/cart.js

fixed merge cart bug

---

client/components/Noodle/SingleNoodle.js
server/api/noodles.js
server/api/orderItems.js
server/api/orders.js
server/api/users.js

added comments and refactored some of the routes'

---

client/components/auth-form.js
client/components/client-react.spec.js
client/store/user.spec.js

some more test spec add ons

---

client/components/Cart/Cart.js
client/components/Cart/CartItem.js
client/components/Cart/Checkout.js
server/api/noodles.js
server/api/orderItems.js
server/api/users.js

finishing touches

---

client/components/Cart/Checkout.js
client/components/User/UserHome.js
client/routes.js
react-express-stripe/frontend/Checkout.js

pay with stripe works

---

client/components/Noodle/AllNoodles.js
client/components/Noodle/SingleNoodle.js
client/components/User/UserHome.js
client/components/User/UserOrders.js

put allnoodles into cards

---

client/components/Noodle/AllNoodles.js
client/components/User/UpdateUser.js
client/store/noodles.js
script/seed.js
server/db/models/noodle.js

filter by veggie

---

client/app.js
client/components/Footer.js
client/components/UserLogin.js
client/components/UserSignup.js
client/components/auth-form.js

fixed auth form bug

---

client/components/UserLogin.js
client/components/UserSignup.js
client/components/auth-form.js

displayName to displayname

---

client/components/Noodle/AllNoodles.js

filtered all

---

server/auth/google.js

trying to fix google sign up

---

server/auth/google.js

done with google finally

---

react-express-stripe/frontend/constants/stripe.js

stripe fixed

---

client/components/Noodle/SingleNoodle.js

fixed single noodle image

---

client/components/Cart/Cart.js
client/components/User/UserHome.js
client/components/User/UserOrders.js
client/store/cart.js
client/store/user.spec.js
server/api/utils.js
server/auth/index.js

cleaned console logs and comments

---

client/components/client-react.spec.js
client/components/user-home.spec.js
server/api/tests/orders.spec.js
server/api/users.spec.js

added couple more test specs

---

client/components/Admin/Admin.js
client/components/Admin/UserList.js
client/components/Cart/CartItem.js
client/components/auth-form.js
client/components/client-react.spec.js
client/store/user.spec.js
server/api/noodles.spec.js
server/api/users.js
server/api/users.spec.js
server/api/utils.js
server/db/models/noodle.spec.js
server/db/models/order.spec.js
server/db/models/user.spec.js

added test specs

---

server/api/tests/orders.spec.js
server/api/users.spec.js

changed some test specs to pending
